### ISSUE TITLE
saveCurrentRGBD function

### ISSUE THREAD

**Issue by JohnWickPixel** [AoLyu/capture_pointcloud_with_realsenseD435#3]
Hello,
I'm trying your project but I am having problems with the saveCurrentRGBD function everytime I try to save the bag video to RGBD it won't work. 
I am using Python3 in MacOS platform.
I am looking forward to your answer, Thanks.

**Comment by AoLyu** [comment]
Maybe it's due to the version of the libs, especially the open3d (It develops very fast) , It worked well on my Ubuntu 16.04 (OpenCV == 4.1.0.25  ,PyRealsense2 == 2.17.1.457 ,Open3D == 0.8.0) (I've graduated for several month and it's now hard for me to continue to maintain this repo). 
You can refer to the official pyrealsense [examples](https://github.com/IntelRealSense/librealsense/tree/master/wrappers/python/examples)  and [Open3D documentation] (http://www.open3d.org/docs/release/). 
Wish you could solve your problem successfully.

**Comment by JohnWickPixel** [comment]
Thanks @AoLyu i solved the problem yesterday by updating the libraries. We can consider this issue closed.
