### ISSUE TITLE
Implementation of 3D Object Reconstruction with L515 Lidar camera

### ISSUE THREAD

**Issue by sharish33** [AoLyu/capture_pointcloud_with_realsenseD435#5]
Hi,

I am trying to implement the 3D Object Reconstruction with L515 lidar camera instead of D435. During initialization i changed the config.enable parameters compatible to L515.(currently L515 only support 640x480/1024x768 for Depth and 1920x1080/1280x720 for Color). But when I run the code - interfaceVersion.py, colour image is being generated but the Point cloud window is showing blank. Please can you let know your suggestions in resolving the issue.

Best Regards,
Hareesh

**Comment by AoLyu** [comment]
Hi @sharish33，sorry to reply late.  Maybe you can use a chessboard to calculate the align matrix of the L515 color image and the depth image first, just like [iai_kinect2](https://github.com/code-iai/iai_kinect2)(1920*1080 for origin color image ,  512*424 for origin depth map) . After getting the same size color and depth images, you can generate the colored point cloud. I skiped this step because Realsense D435 can deliver aligned RGBD images directly. 

> "the Point cloud window is showing blank" means the point cloud is empty or not in the current view (try to drag the blank randomly or print the points array to see whether it is null).

Hope you have already solved the issue !

**Comment by AoLyu** [comment]
Hi @sharish33，sorry to reply late. Maybe you can use a chessboard to calculate the align matrix of the L515 color image and the depth image first, just like [iai_kinect2](https://github.com/code-iai/iai_kinect2)(1920x1080 for origin color image , 512x424 for origin depth map) . After getting the same size color and depth images, you can generate the colored point cloud. I skiped this step because Realsense D435 can deliver aligned RGBD images directly.

>"the Point cloud window is showing blank" 

means the point cloud is empty or not in the current view  of the window(try to drag the blank randomly or print the points array to see whether it is null).

Hope you have already solved the issue !
